fineract:
  api-url: "http://localhost:8080/fineract-provider/api/v1"

zeebe:
  client:
    broker:
      gateway-address: "localhost:26500"

baasflow:
  events:
    disabled: true

logging:
  level:
    root: trace
    org.eclipse.jetty: info
    io.camunda: info
    sun: info
    jdk: info
    java: info
    javax: info
    org.mifos.connector: trace
