camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

dfspids: "DFSPID"

fineract:
  api-url: "http://localhost:8080/fineract-provider/api/v1"
  current-account-api: "/current-accounts/"
  datatable-query-api: "/datatables/dt_client_account_mapping/query"
  flags-query-api: "/datatables/dt_savings_account_flags/query"
  flags-column-filter: "savings_account_id"
  flags-result-columns: "flag_code"
  current-account-flags-result-columns: "flag_code"
  column-filter: "iban"
  result-columns: "conversion_account_id,disposal_account_id,internal_account_id"
  current-account-result-columns: "status_type,account_no,external_id,id,product_idg"
  incoming-money-api: "/savingsaccounts/"
  transaction-details-api: "/datatables/dt_savings_transaction_details /"
  datatable-name: "transaction_details"
  locale: "en"
  paymentType:
    paymentTypeExchangeFiatCurrencyId: 5
    paymentTypeIssuingECurrencyId: 7
    paymentTypeExchangeECurrencyId: 8
    paymentTypeExchangeToFiatCurrencyId: 6
    paymentTypeFeeId: 1
  generalLedger:
    glLiabilityToCustomersInFiatCurrencyId: 10
    glLiabilityAmountOnHoldId: 14
  idempotency:
    count: 3
    interval: 200
    key-header-name: "Idemptency-Key"

zeebe:
  client:
    connection-mode: ADDRESS
    security:
      plaintext: true
  broker:
    contactpoint: "localhost:26500"

ams:
  local:
    enabled: true
    version: 1.2
    keystore-path: keystore.jks
    keystore-password: openmf
    interop:
      host: http://localhost:8080
      base-url: /fineract-provider/api/v1
      quotes-path: ${ams.local.interop.base-url}/interoperation/quotes
      parties-path: ${ams.local.interop.base-url}/interoperation/parties/{idType}/{idValue}
      transfers-path: ${ams.local.interop.base-url}/interoperation/transfers
      accounts-path: ${ams.local.interop.base-url}/interoperation/accounts/{externalAccountId}
    customer:
      host: http://localhost:8080
      base-url: /fineract-provider/api/v1
      path: ${ams.local.customer.base-url}/clients/{clientId}
      image: ${ams.local.customer.base-url}/clients/{clientId}/images
    account:
      host: http://localhost:8080
      base-url: /fineract-provider/api/v1
      savingsaccounts-path: ${ams.local.account.base-url}/savingsaccounts
    auth:
      host: http://localhost:8080

baasflow:
  events:
    disabled: true
