version: 2.1
orbs:
  docker-buildx: devarsh/docker-buildx-orb@0.1.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:13.0-buster-node-browsers-legacy

jobs:
  build_and_push_tag_image:
    executor: docker-executor
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - docker-buildx/install
      - run:
          name: Check if Docker image tag exists
          command: |
            IMAGE_TAG=$CIRCLE_TAG
            if curl -s -f -u "$DOCKERHUB_USERNAME":"$DOCKERHUB_PASSWORD" "https://hub.docker.com/v2/repositories/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tags/$IMAGE_TAG" > /dev/null; then
              echo "Skipping the build and push as the tag $IMAGE_TAG already exists in Docker Hub."
              exit 0
            fi
      - run:
          name: Build Application
          command: ./gradlew bootJar
      - docker-buildx/build-and-push:
          image-name: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" # Using repo name
          tag: "$CIRCLE_TAG"

  build_and_push_branch_image:
    executor: docker-executor
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - docker-buildx/install
      - run:
          name: Build Application
          command: |
            ./gradlew checkstyleMain
            ./gradlew clean bootJar
      - run:
          name: Sanitize Branch Name
          command: |
            echo "export SANITIZED_BRANCH=$(echo $CIRCLE_BRANCH | sed 's/\//-/g')" >> $BASH_ENV
      - docker-buildx/build-and-push:
          image-name: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
          tag: "${SANITIZED_BRANCH}-latest"

  build_and_push_latest_image:
    executor: docker-executor
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - docker-buildx/install
      - run:
          name: Build Application
          command: |
            ./gradlew checkstyleMain
            ./gradlew clean bootJar
      - docker-buildx/build-and-push:
          image-name: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" # Using repo name
          tag: "latest"

workflows:
  version: 2
  build-and-push-tags:
    jobs:
      - build_and_push_tag_image:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
          context:
            - DOCKER
  build-and-push-branches:
    jobs:
      - build_and_push_branch_image:
          context:
            - DOCKER
      - build_and_push_latest_image:
          requires:
            - build_and_push_branch_image
          context:
            - DOCKER
